import { NavBar, Footer } from '@/components';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin=''
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Roboto+Serif&display=swap'
          rel='stylesheet'
        />
      </head>
      <body className="dark:bg-black/90 bg-[#edf2fb]">
        <nav>
          <NavBar />
        </nav>
        {children}
        <Footer />
      </body>
    </html>
  );
}
